### ISSUE TITLE
When deployed with grafana, hydra:oauth relation needs to be reformed

### ISSUE THREAD

**Issue by slapcat** [canonical/iam-bundle#306]
### Bug Description

I'm noticing an issue when deploying a bundle with Canonical IAM and grafana. Grafana does not show the `Sign in with external identity provider` link until I remove and readd the relation between hydra:oauth and grafana. This does not happen if I deploy the bundle as is, then add grafana and the relations after.

### To Reproduce

1. Create grafana overlay:
```
applications:
  grafana:
    charm: ch:grafana-k8s
    channel: latest/stable
    series: focal
    scale: 1
    storage:
      database: kubernetes,1,1024M
relations:
  - [grafana:ingress, traefik-public:traefik-route]
  - [grafana:oauth, hydra:oauth]
  - [grafana:receive-ca-cert, self-signed-certificates:send-ca-cert]
```
2. Deploy Canonical IAM with grafana overlay: `juju deploy --trust --channel=latest/edge identity-platform --overlay grafana.yaml`
3. Visit grafana UI to see if `Sign in with external identity provider` link is available. It should not be.
4. Remove and readd the relation:
```
juju remove-relation hydra:oauth grafana:oauth
juju relate hydra:oauth grafana:oauth
```
5. Check grafana UI again after the units settle. The link should now be available.
### Environment

Channel: latest/edge
Environment: 3-node charmed microk8s cluster, version 1.28/stable
Juju version: 3.6

### Relevant log output

```shell
None.
```

**Comment by pik4ez-canonical** [comment]
Hello Jake! Thank you for reaching out.

May I ask you to try and add the `trust: true` flag to the overlay:
```
applications:
  grafana:
    trust: true
    charm: ch:grafana-k8s
    ...
```

When I tried to reproduce the issue in my environment (Multipass VM), the problem was that Grafana couldn't finish the reconciliation because of Kubernetes service account permission issue.

If it doesn't help, could you please provide relevant logs: `juju status` and `juju debug-log` for the failing units.
